export const GET_APPLIED_JOBS_REQUEST = "GET_APPLIED_JOBS_REQUEST";
export const GET_APPLIED_JOBS_SUCCESS = "GET_APPLIED_JOBS_SUCCESS";
export const GET_APPLIED_JOBS_FAIL = "GET_APPLIED_JOBS_FAIL";

export const CREATE_APPLICATION_REQUEST = "CREATE_APPLICATION_REQUEST";
export const CREATE_APPLICATION_SUCCESS = "CREATE_APPLICATION_SUCCESS";
export const CREATE_APPLICATION_FAIL = "CREATE_APPLICATION_FAIL";

export const GET_SINGLE_APPLICATION_REQUEST = "GET_SINGLE_APPLICATION_REQUEST";
export const GET_SINGLE_APPLICATION_SUCCESS = "GET_SINGLE_APPLICATION_SUCCESS";
export const GET_SINGLE_APPLICATION_FAIL = "GET_SINGLE_APPLICATION_FAIL";

export const DELETE_APPLICATION_REQUEST = "DELETE_APPLICATION_REQUEST";
export const DELETE_APPLICATION_SUCCESS = "DELETE_APPLICATION_SUCCESS";
export const DELETE_APPLICATION_FAIL = "DELETE_APPLICATION_FAIL";

export const UPDATE_APPLICATION_STATUS_REQUEST =
  "UPDATE_APPLICATION_STATUS_REQUEST";
export const UPDATE_APPLICATION_STATUS_SUCCESS =
  "UPDATE_APPLICATION_STATUS_SUCCESS";
export const UPDATE_APPLICATION_STATUS_FAIL = "UPDATE_APPLICATION_STATUS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
