export const COMPANY_LOGIN_REQUEST = "COMPANY_LOGIN_REQUEST";
export const COMPANY_LOGIN_SUCCESS = "COMPANY_LOGIN_SUCCESS";
export const COMPANY_LOGIN_FAIL = "COMPANY_LOGIN_FAIL";
export const COMPANY_LOGOUT = "COMPANY_LOGOUT";

export const COMPANY_REGISTER_REQUEST = "COMPANY_REGISTER_REQUEST";
export const COMPANY_REGISTER_SUCCESS = "COMPANY_REGISTER_SUCCESS";
export const COMPANY_REGISTER_FAIL = "COMPANY_REGISTER_FAIL";

export const COMPANY_LOAD_REQUEST = "COMPANY_LOAD_REQUEST";
export const COMPANY_LOAD_SUCCESS = "COMPANY_LOAD_SUCCESS";
export const COMPANY_LOAD_FAIL = "COMPANY_LOAD_FAIL";

export const COMPANY_UPDATE_PROFILE_REQUEST = "COMPANY_UPDATE_PROFILE_REQUEST";
export const COMPANY_UPDATE_PROFILE_SUCCESS = "COMPANY_UPDATE_PROFILE_SUCCESS";
export const COMPANY_UPDATE_PROFILE_FAIL = "COMPANY_UPDATE_PROFILE_FAIL";

export const COMPANY_UPDATE_LOGO_REQUEST = "COMPANY_UPDATE_LOGO_REQUEST";
export const COMPANY_UPDATE_LOGO_SUCCESS = "COMPANY_UPDATE_LOGO_SUCCESS";
export const COMPANY_UPDATE_LOGO_FAIL = "COMPANY_UPDATE_LOGO_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
