// Common skills list
export const commonSkills = [
  // Programming Languages
  "JavaScript",
  "Python",
  "Java",
  "C++",
  "C#",
  "TypeScript",
  "PHP",
  "Ruby",
  "Swift",
  "Kotlin",
  "Go",
  "Rust",
  "Scala",
  "Perl",
  "R",
  "MATLAB",

  // Web Development
  "HTML",
  "CSS",
  "React",
  "Angular",
  "Vue.js",
  "Next.js",
  "Node.js",
  "Express.js",
  "Django",
  "Flask",
  "Laravel",
  "Spring Boot",
  "ASP.NET",

  // Mobile Development
  "React Native",
  "Flutter",
  "Android Development",
  "iOS Development",
  "Xamarin",
  "Ionic",

  // Databases
  "SQL",
  "MySQL",
  "PostgreSQL",
  "MongoDB",
  "Redis",
  "Cassandra",
  "Oracle",
  "SQLite",
  "Firebase",
  "DynamoDB",

  // Cloud & DevOps
  "AWS",
  "Azure",
  "Google Cloud",
  "Docker",
  "Kubernetes",
  "Jenkins",
  "Git",
  "CI/CD",
  "Terraform",
  "Ansible",
  "Linux",
  "Shell Scripting",

  // Data Science & AI
  "Machine Learning",
  "Deep Learning",
  "Data Science",
  "Data Analysis",
  "TensorFlow",
  "PyTorch",
  "Pandas",
  "NumPy",
  "Scikit-learn",
  "NLP",
  "Computer Vision",

  // Design & UI/UX
  "UI/UX Design",
  "Figma",
  "Adobe XD",
  "Sketch",
  "Photoshop",
  "Illustrator",
  "InDesign",
  "Wireframing",
  "Prototyping",

  // Project Management & Methodologies
  "Agile",
  "Scrum",
  "Kanban",
  "Project Management",
  "JIRA",
  "Trello",
  "Confluence",
  "Waterfall",

  // Soft Skills
  "Communication",
  "Leadership",
  "Problem Solving",
  "Team Management",
  "Time Management",
  "Critical Thinking",
  "Adaptability",
  "Creativity",
  "Collaboration",

  // Testing & Quality
  "Unit Testing",
  "Integration Testing",
  "E2E Testing",
  "Jest",
  "Selenium",
  "Cypress",
  "QA",
  "Test Automation",

  // Security
  "Cybersecurity",
  "Network Security",
  "Application Security",
  "Penetration Testing",
  "Security Analysis",

  // Other Technical Skills
  "REST APIs",
  "GraphQL",
  "Microservices",
  "System Design",
  "Architecture",
  "Performance Optimization",
  "Code Review",
  "Technical Documentation",
];
